version: '3.3'

services:
  mfcoind:
    image: kamehb/mfc-wallet-daemon
    volumes:
      - ./data/daemon:/data
    command:
      - -server
      - -rpcuser=anonymous
      - -rpcpassword=anonymous
      - -disablewallet=1
      - -reindex
      - -rpcallowip=0.0.0.0/0
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf/90-nginx-before-start.sh:/docker-entrypoint.d/90-nginx-before-start.sh
      - ./sockets:/sockets
