version: '3.3'

services:
  mfcoind:
    image: kamehb/mfc-wallet-daemon
    volumes:
      - ./data/daemon:/data
    command:
      - -server
      - -rpcuser=anonymous
      - -rpcpassword=anonymous
      - -disablewallet=1
      - -reindex
      - -rpcallowip=0.0.0.0/0
    restart: always
  proxy:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./proxy:/app
    environment:
      TDOMAIN: mfcoind
    ports:
      - 22825:22825
    depends_on:
      - mfcoind
